### ISSUE TITLE
Infinity.tsx - None of these files exist

### ISSUE THREAD

**Issue by leymytel** [duongdev/phosphor-react-native#15]
![Screenshot from 2022-02-21 12-47-55](https://user-images.githubusercontent.com/38193378/154958411-0c4dc942-221d-42ce-a770-89c886503154.png)

I'm getting this error since I upgraded from `0.4.0` to `1.1.1`

**Comment by FrancoTanzarellaEviivo** [comment]
I have latest (1.1.2) with the same issue but different icons.
![Screenshot 2022-12-09 at 10 56 57](https://user-images.githubusercontent.com/77055637/206687127-25cf4551-82f9-488f-929b-dee9de716b9f.png)
