### ISSUE TITLE
It's not working with Expo Snack

### ISSUE THREAD

**Issue by brunomacedo** [duongdev/phosphor-react-native#19]
I'm trying to install in **[Expo Snack](https://snack.expo.dev/)**, but it doesn't work. I couldn't find the error. 
It always continues in `Resolving`

```
Resolving 'phosphor-react-native@*' ...Dependencies
```

<img alt="image" src="https://user-images.githubusercontent.com/10273138/173129186-c44c1e2a-f5ff-49f2-b2f3-b844af596a98.png">

**Comment by duongdev** [comment]
Hey Bruno, it seems to be Expo Snack issue. Some packages are not able to be resolved by Expo Snack. https://github.com/expo/snack/issues/279

**Comment by brunomacedo** [comment]
> Hey Bruno, it seems to be Expo Snack issue. Some packages are not able to be resolved by Expo Snack. [expo/snack#279](https://github.com/expo/snack/issues/279)
> 
> Edit: I've tried and got the same issue.

Thanks @duongdev
