### ISSUE TITLE
Phosphor + Expo: JavaScript heap out of memory

### ISSUE THREAD

**Issue by caioedut** [duongdev/phosphor-react-native#24]
After using phosphor-react-native, everytime I try to build a new app version with Expo EAS, I caught "JavaScript heap out of memory" (too many files).

There is no way to phosphor-react-native distribution to be smaller?

I also tried to set Node memory to 12GB.

I use `import * as Icon from "phosphor-react-native";` and I need it.

**Comment by Chiliseo** [comment]
try to used this format
import User from 'phosphor-react-native/src/icons/User'

:)
