### ISSUE TITLE
Update to last release v2.0.0

### ISSUE THREAD

**Issue by brugaspar** [duongdev/phosphor-react-native#27]
Update to the last release of Phosphor Icons to get the new icons. The last release is **v2.0.0**.

**Comment by K0R1NGA69** [comment]
Hi there! I'm getting this error after updating to v2.0: Invariant Violation: View config getter callback for component `path` must be a function (received `undefined`). Make sure to start component names with a capital letter.

This error is located at:
    in path
    in svg (created by IconBase)
    in IconBase (created by Star)
    in Star (created by UserRecords)
    in RCTView (created by View)
    in View
    in Unknown

expo 48

**Comment by mrkpatchaa** [comment]
I just created a PR #33 with this. Hopefully this get merged.
