### ISSUE TITLE
Help with maintenance?

### ISSUE THREAD

**Issue by jhhayashi** [duongdev/phosphor-react-native#34]
Hey Dustin, thanks for all of the work putting together this library.

This library is linked to from the [phosphor icon README](https://github.com/phosphor-icons/homepage#readme), so it would be helpful to better understand your willingness to maintain and host it.

If you'd like to keep hosting the repo, but are looking for help maintaining it, I'd be happy to help. If you're no longer interested in hosting the repo, I'd also volunteer to take it (and the npm releases) over.

**Comment by jhhayashi** [comment]
Sounds great. I have an active project that depends on this project, so I'm excited to help.

My npmjs user ID is `jhhayashi`

**Comment by jhhayashi** [comment]
I got both invites and should be all set up 🚀

**Comment by duongdev** [comment]
Cool. Could you please help release the latest changes to npm? Thank you! 🎉

**Comment by jhhayashi** [comment]
Yep, will do!

**Comment by duongdev** [comment]
@jhhayashi As this repo belongs to my personal Github account, I can only add you as collaborator. Because we have a protected branch rule on `main`, its PRs need to have at least 1 approval to be merged. I can remove that requirements so perhaps you can merge your PRs without my approval.

**Comment by duongdev** [comment]
@jhhayashi I have disabled "Require a pull request before merging" and enabled "Allow force pushes" to your github username. Could you try again?

**Comment by jhhayashi** [comment]
Force pushing to main still fails with a couple errors:
```
remote: error: GH006: Protected branch update failed for refs/heads/main.                                                                                                                                   
remote: error: Required status check "run" is expected.
```

But I am able to create PRs and merge them. The downside is that `release-it` will not be able to manage the tagging/releasing because the commit hash changes when merging the PR (and the tag that `release-it` creates will be pointing to the wrong commit). The workaround is for me to create the tag/release manually, and maybe eventually have this happen in a Github Action
