### ISSUE TITLE
disappear the point in some Icons without weight='fill'

### ISSUE THREAD

**Issue by Choyeongdeok** [duongdev/phosphor-react-native#4]
Thank you for creating this Icon library, but I got a problem.
Some of these icons which have point don't show point without weight='fill'(in regular)

see this capture of Info icon below(also in Smiley)
![스크린샷 2021-09-29 오전 11 38 53](https://user-images.githubusercontent.com/54658590/135193796-78ea525d-d55e-4ed1-b94b-618a5a83ad9e.png)

**Comment by duongdev** [comment]
Hey @Choyeongdeok,

To reproduce easier, could you give me the screenshot and the code of these 2 scenarios? Did you try to change the colour of the icon?

**Comment by Choyeongdeok** [comment]
This is default

![스크린샷 2021-09-30 오후 2 15 34](https://user-images.githubusercontent.com/54658590/135391458-1e9edcf7-c07e-463c-b7af-cddf9c1207a5.png
![스크린샷 2021-09-30 오후 2 15 51](https://user-images.githubusercontent.com/54658590/135391484-1ae22882-022f-4267-9a23-d4d281b6dd61.png)
)


and this is weight='fill
![스크린샷 2021-09-30 오후 2 17 26](https://user-images.githubusercontent.com/54658590/135391664-7250df6b-e6c7-4826-9944-2d575e6ba981.png)
![스크린샷 2021-09-30 오후 2 18 05](https://user-images.githubusercontent.com/54658590/135391688-2b3f6e53-062a-4bf6-b830-daeb0647f11a.png)

**Comment by duongdev** [comment]
@Choyeongdeok Thank you for reporting the issue. I have figured out the issue and will fix it ASAP.
