### ISSUE TITLE
Is possible to change duotone weight shadow color?

### ISSUE THREAD

**Issue by EduardoJM** [duongdev/phosphor-react-native#41]
We have the duotone weight that add a shadow inside the icon:

![image](https://github.com/duongdev/phosphor-react-native/assets/20397491/fcbfe3f5-e2e2-4acc-b8a8-623227a63561)

Is possible to change the shadow color?

**Comment by bodo6778** [comment]
If someone still needs this, I've made a fork to fix this problem: https://github.com/bodo6778/phosphor-react-native-custom-duotone

**Comment by mrkpatchaa** [comment]
Hi @bodo6778 can I backport your changes to this repo? I will make some tests to make sure it's working as expected.
Thank you.

**Comment by bodo6778** [comment]
> Hi @bodo6778 can I backport your changes to this repo? I will make some tests to make sure it's working as expected. Thank you.

Sure
