### ISSUE TITLE
cant' install in expo with react native and npm

### ISSUE THREAD

**Issue by JoaoKremerDev** [duongdev/phosphor-react-native#45]

**Comment by carl0smat3us** [comment]
I'm facing the same problem.

**Comment by rmrantunes** [comment]
Apparently, expo version >= 50 and phosphor-react-native version 2 are compatible with react-native-svg version 13.9.0, as I just test it.

**Comment by kkjdaniel** [comment]
Using Expo `>= v50` and running `npx expo install react-native-svg` resolved this issue for me.

**Comment by Alan-Graton** [comment]
I don't know why, but can't install neither `react-native-svg` or `phosphor-react-native` in my Expo 50 project ;-; I ran the commands and the terminal never leaves the "installing" state
