### ISSUE TITLE
Add aria-label?

### ISSUE THREAD

**Issue by leononame** [duongdev/phosphor-react-native#47]
When using react-native-web, my browser complaints that the svg isn't labelled correctly when the icon is diplayed. Should the generated code maybe add `aria-label` to each `<Svg` element automatically?

**Comment by mrkpatchaa** [comment]
@leononame Version 2.1.2 is now published on NPM. It adds support for `title` and `titleId` props in order to handle accessibility issues. 
There is no default title as it depends a lot on usage I would say.
