### ISSUE TITLE
Add support for className when icon has background

### ISSUE THREAD

**Issue by brugaspar** [duongdev/phosphor-react-native#48]
Add support for **className** when icon has weight "fill" or "duotone". When you set weight to _thin_, _light_, _regular_ or _bold_, the className works fine, because the "fill" prop in SVG is `currentColor`, but when the weight is _fill_ or _duotone_, the "fill" prop in SVG is set to `props.color`, losing the color passed through **className**. 

I'm using Nativewind, so when I use something like "text-zinc-800", it only works with weights that don't have background, e.g. regular.

![coldcode](https://github.com/duongdev/phosphor-react-native/assets/54087072/791836e7-6ad0-49a8-b124-f183b3579de1)

I did some tests and I think this could be removed, since "currentColor" works for both "fill" and "duotone" as well.

**Comment by mrkpatchaa** [comment]
Hi @brugaspar let me take a look at it.
