### ISSUE TITLE
 ERROR  Invariant Violation: View config getter callback for component `path` must be a function (received `undefined`). Make sure to start component names with a capital letter.

### ISSUE THREAD

**Issue by gabrielrabelof** [duongdev/phosphor-react-native#49]
ERROR  Invariant Violation: View config getter callback for component `path` must be a function (received `undefined`). Make sure to start component names with 
a capital letter.

![bug](https://github.com/duongdev/phosphor-react-native/assets/105120958/43638d1d-8683-4855-9046-8543dbe249ad)

**Comment by mrkpatchaa** [comment]
Hi @gabrielrabelof this repository is for phosphor react native. You are using the react version. 
You should open your issue here https://github.com/phosphor-icons/react
Thanks.
