### ISSUE TITLE
New Icons

### ISSUE THREAD

**Issue by TonySilva7** [duongdev/phosphor-react-native#51]
There are new icons for the web version. Is there any prospect of adding them to the React Native version?

**Comment by mrkpatchaa** [comment]
Hi @jhhayashi can you check this please?

**Comment by shaundon** [comment]
I would love this too – I did attempt to make a PR to do it myself, but I couldn't figure out how to update them 🙈 May revisit it when I get a chance though.

**Comment by mrkpatchaa** [comment]
@shaundon the generated icons are not in the repository anymore. Someone with NPM credentials needs to run the generate script and then release it to NPM. 
@jhhayashi has been granted access by @duongdev back in 2023.
Check the discussion here: https://github.com/duongdev/phosphor-react-native/pull/33

**Comment by shaundon** [comment]
Ah, thanks for the extra context!

**Comment by hadnet** [comment]
Any updates on this?

**Comment by hadnet** [comment]
This package is updated https://www.npmjs.com/package/react-native-phosphor?activeTab=versions

**Comment by mrkpatchaa** [comment]
@hadnet it's unfortunate that we need to duplicate packages just for an update. I remember I've created one myself when upgrading icons (deleted now)
Now the update to NPM takes barely 5 min, but no maintainer here can do it 😞 
@jhhayashi @duongdev can you please add more people as maintainers and explain how to publish new updates? 
Thanks.

**Comment by duongdev** [comment]
@mrkpatchaa I am happy to. Do you want to give a help?

**Comment by mrkpatchaa** [comment]
@duongdev Yes I can help. Thanks.

**Comment by duongdev** [comment]
@mrkpatchaa Added you as repo's collaborator. Please send me your npmjs username as well

**Comment by mrkpatchaa** [comment]
Hi @duongdev  my username is mrkpatchaaadmin. You can also try with my email kraymond70@gmail.com

**Comment by duongdev** [comment]
@mrkpatchaa Added you as contributor. Please help to update the package. Thank you very much!

**Comment by mrkpatchaa** [comment]
@duongdev it seems like I cannot push to main. Can you check please? 
Version 2.1.0 published on NPM https://www.npmjs.com/package/phosphor-react-native/v/2.1.0

**Comment by duongdev** [comment]
@mrkpatchaa Thank you very much! Btw, you might need to open a PR to main instead of commit directly.
