### ISSUE TITLE
Support for new Phosphor Icons

### ISSUE THREAD

**Issue by suryamthapa** [duongdev/phosphor-react-native#56]
There are a lot of icons added recently to the collection as seen on the official site (https://phosphoricons.com/).

Need support for those added icons in this library.

**Comment by hadnet** [comment]
Hey, man @duongdev . Any update on this?

**Comment by hadnet** [comment]
This package is updated https://www.npmjs.com/package/react-native-phosphor?activeTab=versions

**Comment by mrkpatchaa** [comment]
@hadnet version 2.1.0 on npm now contains all the new icons.
