### ISSUE TITLE
Extremely slow on first render

### ISSUE THREAD

**Issue by rogerkerse** [duongdev/phosphor-react-native#57]
Test reproduction:
1. Have `react-navigation` application and add any icon to second screen
2. On iOS simulator navigate to second screen

First time navigating to second screen with the icon it freezes for 1-2 seconds (it doesn't when no icon is present). Second navigation to that screen is quick.

Does anyone else have this problem?

And it happens only in development mode. In release it is not visibile.

**Comment by Boztown** [comment]
I am also seeing this problem. I'm including the icon in a dialog box and when I render that dialog it actually takes upwards of 30 seconds for it to open. By process of elimination it came down to the Phosphor icon I was using. Once it's loaded once it remains normal/fast until I fully reload the app again.

**Comment by Boztown** [comment]
So I had a vague memory of us running into this before and knowing the answer. It just came back to me.

If you're importing like this:

```
import { Warning } from "phosphor-react-native";
```

Don't. Import like this:

```
import Warning from "phosphor-react-native/src/regular/Warning";
```

I think in development mode assets are being served up by Metro and for whatever reason importing from the root of the library like `import { Warning } from "phosphor-react-native"` ends up effectively loading up all the icons. I don't know this for sure but I believe a co-worker traced this through more than I have and found something to this effect. Either way, this is definitely the problem for us and took me having to rediscover a comment we had made about watching that import style.

**Comment by alexrififi** [comment]
> Import like this:
> 
> ```
> import Warning from "phosphor-react-native/src/regular/Warning";
> ```

You can import it like that, also without slow render:

```typescript
import Warning from 'phosphor-react-native/src/icons/Warning'
``` 

The advantage is that **weight** remains under control

**Comment by daxaxelrod** [comment]
Holy crap this was exactly my issue
