### ISSUE TITLE
Expo: phosphor-react-native v2.0.0 unable to resolve imports for web

### ISSUE THREAD

**Issue by dieguezguille** [duongdev/phosphor-react-native#58]
I encountered this error using Expo 51.0.21. Seems that the default exports for the library resolve fine on native but when building for web they resolve to undefined. I tried importing like this:  `import * as Icons` and the logs show `Icon` resolves to a React Context object instead of the actual SVG icon. 

For now, we chose to downgrade to the previous version, `1.1.2` which works on all platforms.

**Comment by agathe-lighthouse** [comment]
same! :(

**Comment by mrkpatchaa** [comment]
@dieguezguille I will take a look at it. 👀

**Comment by mrkpatchaa** [comment]
@agathe-lighthouse @dieguezguille version 2.1.1 is published on NPM and fixes the issue.

**Comment by agathe-lighthouse** [comment]
@mrkpatchaa Thanks a lot!!:) I can confirm that the web is now running correctly. However, there is still an issue with the build on web because of this error : ```
ERROR in ./node_modules/phosphor-react-native/lib/module/index.js 4:0-65
export 'IconWeight' (reexported as 'IconWeight') was not found in './lib' (possible exports: IconContext)
```

**Comment by mrkpatchaa** [comment]
Hi @agathe-lighthouse  it should be fixed in 2.2.1 
Please check. Thank you.
