### ISSUE TITLE
How to bump phosphor-icons version?

### ISSUE THREAD

**Issue by Joeao** [duongdev/phosphor-react-native#9]
### Documentation Request

I'm trying to generate icons from https://github.com/phosphor-icons/phosphor-icons/ v1.4.

When copying [`phosphor-icons/assets`](https://github.com/phosphor-icons/phosphor-react/tree/master/assets) into [`phosphor-react-native/svgs`](https://github.com/duongdev/phosphor-react-native/tree/main/svgs) I notice that each `.svg` differs. Copying from [`phosphor-react/assets`](https://github.com/phosphor-icons/phosphor-react/tree/master/assets) to `phosphor-react-native/svgs` also shows a difference in structure. So I'm wondering where are the assets in this repo's `svgs` directory sourced from? If this is documented in the repository then it should be easier for other users to bring this repo up to date and submit pull requests.

**Comment by duongdev** [comment]
Hi @Joeao, thank you for noticing that. I've just tried to replace the icons in this repo with the icons from phosphor-icons@1.3.1 https://github.com/phosphor-icons/phosphor-home/releases/tag/v1.3.1 and there are no differences. So if you want to bump to phosphor-icons v1.4 you can replace the `SVGs` from there to `svgs` here. It should be no problems.

**Comment by Joeao** [comment]
Right, I understand. The svg files are from the release rather than the assets directory in the source code.

Thanks for the info, I'll try it now.

**Comment by duongdev** [comment]
Closed by #11
